include classpath("application.conf")

queues {
  minute-transcription-queue {
    deadLettersQueue {
      name = "minute-transcription-queue-deadletter"
      maxReceiveCount = 4
    }
  }
  minute-transcription-queue-deadletter {}

  minute-llm-queue {
    deadLettersQueue {
      name = "minute-llm-queue-deadletter"
      maxReceiveCount = 4
    }
  }
  minute-llm-queue-deadletter {}
}

node-address {
  protocol = http
  host = "*"
  port = 9324
  context-path = ""
}

rest-sqs {
  enabled = true
  bind-port = 9324
  bind-hostname = "0.0.0.0"
  sqs-limits = relaxed
}