from typing import Any, Protocol

from common.types import WorkerMessage


class QueueService(Protocol):
    name: str

    def __init__(self, queue_name: str, deadletter_queue_name: str, **kwargs): ...

    def receive_message(self, max_messages: int = 10) -> list[tuple[WorkerMessage, Any]]: ...

    def publish_message(self, message: WorkerMessage): ...

    def complete_message(self, receipt_handle: Any): ...

    def deadletter_message(self, message: WorkerMessage, receipt_handle: Any): ...

    def abandon_message(self, receipt_handle: Any): ...

    def purge_messages(self): ...
