from typing import Any, Protocol

from backend.app.minutes.types import WorkerMessage


class QueueService(Protocol):
    name: str

    def receive_message(self) -> list[tuple[WorkerMessage, Any]]: ...

    def publish_message(self, message: WorkerMessage): ...

    def complete_message(self, receipt_handle: Any): ...

    def deadletter_message(self, message: WorkerMessage, receipt_handle: Any): ...

    def abandon_message(self, receipt_handle: Any): ...

    def purge_messages(self): ...
