from typing import Any, Protocol, TypeVar

from pydantic import BaseModel

from common.types import AudioWorkerMessage, WorkerMessage

WorkerMessageType = AudioWorkerMessage | WorkerMessage
MessageT = TypeVar("MessageT", bound=BaseModel)


class QueueService(Protocol[MessageT]):
    name: str

    def __init__(self, queue_name: str, deadletter_queue_name: str, **kwargs): ...

    def receive_message(self, max_messages: int = 10) -> list[tuple[MessageT, Any]]: ...

    def receive_deadletter_message(self, max_messages: int = 10) -> list[tuple[MessageT, Any]]: ...

    def publish_message(self, message: MessageT): ...

    def complete_message(self, receipt_handle: Any): ...

    def complete_deadletter_message(self, receipt_handle: Any): ...

    def deadletter_message(self, message: MessageT, receipt_handle: Any): ...

    def abandon_message(self, receipt_handle: Any, delay_seconds: int = 0): ...

    def abandon_deadletter_message(self, receipt_handle: Any, delay_seconds: int = 0): ...

    def purge_messages(self): ...

    def close(self, *, force: bool = False): ...
