"""empty message

Revision ID: 00a203bcfeaa
Revises: 6757f82ea8b2
Create Date: 2025-02-16 13:17:07.482351

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "00a203bcfeaa"
down_revision: Union[str, None] = "6757f82ea8b2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "transcription",
        "created_datetime",
        existing_type=postgresql.TIMESTAMP(),
        server_default=None,
        existing_nullable=False,
    )
    op.add_column("user", sa.Column("data_retention_days", sa.Integer(), nullable=True))
    op.alter_column(
        "user", "created_datetime", existing_type=postgresql.TIMESTAMP(), server_default=None, existing_nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "created_datetime",
        existing_type=postgresql.TIMESTAMP(),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.drop_column("user", "data_retention_days")
    op.alter_column(
        "transcription",
        "created_datetime",
        existing_type=postgresql.TIMESTAMP(),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
