"""add uploaded documents column

Revision ID: 6757f82ea8b2
Revises: e2c1973fb968
Create Date: 2025-02-13 12:53:56.745581

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6757f82ea8b2"
down_revision: str | None = "e2c1973fb968"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transcription", sa.Column("uploaded_documents", postgresql.JSONB(astext_type=sa.Text()), nullable=True)
    )
    op.alter_column(
        "transcription",
        "created_datetime",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "transcription",
        "updated_datetime",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    op.alter_column(
        "transcription", "dialogue_entries", existing_type=postgresql.JSONB(astext_type=sa.Text()), nullable=True
    )
    op.alter_column(
        "transcription",
        "date",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
    )
    op.alter_column(
        "user",
        "created_datetime",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "user",
        "updated_datetime",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    op.alter_column("user", "email", existing_type=sa.VARCHAR(), nullable=False)
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.alter_column("user", "email", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "user",
        "updated_datetime",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "user",
        "created_datetime",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "transcription",
        "date",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
    )
    op.alter_column(
        "transcription", "dialogue_entries", existing_type=postgresql.JSONB(astext_type=sa.Text()), nullable=False
    )
    op.alter_column(
        "transcription",
        "updated_datetime",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "transcription",
        "created_datetime",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_column("transcription", "uploaded_documents")
    # ### end Alembic commands ###
