"""Add agenda to minute

Revision ID: 9d30f5b926d4
Revises: fb31a5107160
Create Date: 2025-07-21 10:25:28.214416

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9d30f5b926d4"
down_revision: str | None = "fb31a5107160"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("minute", sa.Column("agenda", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("minute", "agenda")
    # ### end Alembic commands ###
