"""empty message

Revision ID: afa8a57e3832
Revises: 00a203bcfeaa
Create Date: 2025-02-16 16:51:36.512418

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "afa8a57e3832"
down_revision: Union[str, None] = "00a203bcfeaa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transcription", "date")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("transcription", sa.Column("date", postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
