"""empty message

Revision ID: e2c1973fb968
Revises: ef2b536ce815
Create Date: 2025-01-12 17:17:13.061508

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e2c1973fb968"
down_revision: str | None = "ef2b536ce815"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transcription",
        sa.Column("minute_versions", postgresql.JSONB(astext_type=sa.Text()), nullable=True, default="[]"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transcription", "minute_versions")
    # ### end Alembic commands ###
