"""add_title_to_transcription

Revision ID: e577c83813f8
Revises: f5556a9ec1ae
Create Date: 2025-05-08 09:13:18.830189

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlmodel import SQLModel


# revision identifiers, used by Alembic.
revision: str = "e577c83813f8"
down_revision: Union[str, None] = "f5556a9ec1ae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("transcription", sa.Column("title", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transcription", "title")
    # ### end Alembic commands ###
