"""add transcription job state table

Revision ID: f5556a9ec1ae
Revises: afa8a57e3832
Create Date: 2024-03-20 13:39:45.123456

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f5556a9ec1ae"
down_revision: str | None = "afa8a57e3832"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transcriptionjobstate",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("file_key", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("error", sa.String(), nullable=True),
        sa.Column("dialogue_entries", JSONB(), nullable=True),
        sa.Column("created_datetime", sa.DateTime(), nullable=False),
        sa.Column("updated_datetime", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_transcriptionjobstate_file_key", "transcriptionjobstate", ["file_key"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_transcriptionjobstate_file_key", table_name="transcriptionjobstate")
    op.drop_table("transcriptionjobstate")
    # ### end Alembic commands ###
