"""Add description to user template

Revision ID: fe0e69c8d4db
Revises: d3dc5dd94d97
Create Date: 2025-09-29 15:07:05.141384

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op
from sqlmodel import AutoString

# revision identifiers, used by Alembic.
revision: str = "fe0e69c8d4db"
down_revision: str | None = "d3dc5dd94d97"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_template",
        sa.Column("description", AutoString(), nullable=False, server_default=""),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_template", "description")
    # ### end Alembic commands ###
