// This file is auto-generated by @hey-api/openapi-ts

import {
  type DefaultError,
  type InfiniteData,
  infiniteQueryOptions,
  queryOptions,
  type UseMutationOptions,
} from '@tanstack/react-query'

import { client } from '../client.gen'
import {
  createChatTranscriptionsTranscriptionIdChatPost,
  createMinuteTranscriptionTranscriptionIdMinutesPost,
  createMinuteVersionMinutesMinuteIdVersionsPost,
  createRecordingRecordingsPost,
  createTranscriptionTranscriptionsPost,
  createUserTemplateUserTemplatesPost,
  deleteChatsTranscriptionsTranscriptionIdChatDelete,
  deleteChatTranscriptionsTranscriptionIdChatChatIdDelete,
  deleteMinuteVersionMinuteVersionsMinuteVersionIdDelete,
  deleteTranscriptionTranscriptionsTranscriptionIdDelete,
  deleteUserTemplateUserTemplatesTemplateIdDelete,
  duplicateUserTemplateUserTemplatesTemplateIdDuplicatePost,
  editUserTemplateUserTemplatesTemplateIdPatch,
  getChatTranscriptionsTranscriptionIdChatChatIdGet,
  getMinuteMinutesMinutesIdGet,
  getMinuteVersionMinuteVersionsMinuteVersionIdGet,
  getRecordingsForTranscriptionTranscriptionsTranscriptionIdRecordingsGet,
  getTemplatesTemplatesGet,
  getTranscriptionTranscriptionsTranscriptionIdGet,
  getUserTemplatesUserTemplatesGet,
  getUserTemplateUserTemplatesTemplateIdGet,
  getUserUsersMeGet,
  healthcheckHealthcheckGet,
  listChatTranscriptionsTranscriptionIdChatGet,
  listMinutesForTranscriptionTranscriptionTranscriptionIdMinutesGet,
  listMinuteVersionsMinutesMinuteIdVersionsGet,
  listTranscriptionsTranscriptionsGet,
  type Options,
  saveTranscriptionTranscriptionsTranscriptionIdPatch,
  updateDataRetentionUsersDataRetentionPatch,
} from '../sdk.gen'
import type {
  CreateChatTranscriptionsTranscriptionIdChatPostData,
  CreateChatTranscriptionsTranscriptionIdChatPostError,
  CreateChatTranscriptionsTranscriptionIdChatPostResponse,
  CreateMinuteTranscriptionTranscriptionIdMinutesPostData,
  CreateMinuteTranscriptionTranscriptionIdMinutesPostError,
  CreateMinuteVersionMinutesMinuteIdVersionsPostData,
  CreateMinuteVersionMinutesMinuteIdVersionsPostError,
  CreateMinuteVersionMinutesMinuteIdVersionsPostResponse,
  CreateRecordingRecordingsPostData,
  CreateRecordingRecordingsPostError,
  CreateRecordingRecordingsPostResponse,
  CreateTranscriptionTranscriptionsPostData,
  CreateTranscriptionTranscriptionsPostError,
  CreateTranscriptionTranscriptionsPostResponse,
  CreateUserTemplateUserTemplatesPostData,
  CreateUserTemplateUserTemplatesPostError,
  DeleteChatsTranscriptionsTranscriptionIdChatDeleteData,
  DeleteChatsTranscriptionsTranscriptionIdChatDeleteError,
  DeleteChatsTranscriptionsTranscriptionIdChatDeleteResponse,
  DeleteChatTranscriptionsTranscriptionIdChatChatIdDeleteData,
  DeleteChatTranscriptionsTranscriptionIdChatChatIdDeleteError,
  DeleteChatTranscriptionsTranscriptionIdChatChatIdDeleteResponse,
  DeleteMinuteVersionMinuteVersionsMinuteVersionIdDeleteData,
  DeleteMinuteVersionMinuteVersionsMinuteVersionIdDeleteError,
  DeleteTranscriptionTranscriptionsTranscriptionIdDeleteData,
  DeleteTranscriptionTranscriptionsTranscriptionIdDeleteError,
  DeleteTranscriptionTranscriptionsTranscriptionIdDeleteResponse,
  DeleteUserTemplateUserTemplatesTemplateIdDeleteData,
  DeleteUserTemplateUserTemplatesTemplateIdDeleteError,
  DuplicateUserTemplateUserTemplatesTemplateIdDuplicatePostData,
  DuplicateUserTemplateUserTemplatesTemplateIdDuplicatePostError,
  EditUserTemplateUserTemplatesTemplateIdPatchData,
  EditUserTemplateUserTemplatesTemplateIdPatchError,
  GetChatTranscriptionsTranscriptionIdChatChatIdGetData,
  GetChatTranscriptionsTranscriptionIdChatChatIdGetError,
  GetChatTranscriptionsTranscriptionIdChatChatIdGetResponse,
  GetMinuteMinutesMinutesIdGetData,
  GetMinuteMinutesMinutesIdGetError,
  GetMinuteMinutesMinutesIdGetResponse,
  GetMinuteVersionMinuteVersionsMinuteVersionIdGetData,
  GetMinuteVersionMinuteVersionsMinuteVersionIdGetError,
  GetMinuteVersionMinuteVersionsMinuteVersionIdGetResponse,
  GetRecordingsForTranscriptionTranscriptionsTranscriptionIdRecordingsGetData,
  GetRecordingsForTranscriptionTranscriptionsTranscriptionIdRecordingsGetError,
  GetRecordingsForTranscriptionTranscriptionsTranscriptionIdRecordingsGetResponse,
  GetTemplatesTemplatesGetData,
  GetTemplatesTemplatesGetError,
  GetTemplatesTemplatesGetResponse,
  GetTranscriptionTranscriptionsTranscriptionIdGetData,
  GetTranscriptionTranscriptionsTranscriptionIdGetError,
  GetTranscriptionTranscriptionsTranscriptionIdGetResponse,
  GetUserTemplatesUserTemplatesGetData,
  GetUserTemplatesUserTemplatesGetError,
  GetUserTemplatesUserTemplatesGetResponse,
  GetUserTemplateUserTemplatesTemplateIdGetData,
  GetUserTemplateUserTemplatesTemplateIdGetError,
  GetUserTemplateUserTemplatesTemplateIdGetResponse,
  GetUserUsersMeGetData,
  GetUserUsersMeGetError,
  GetUserUsersMeGetResponse,
  HealthcheckHealthcheckGetData,
  ListChatTranscriptionsTranscriptionIdChatGetData,
  ListChatTranscriptionsTranscriptionIdChatGetError,
  ListChatTranscriptionsTranscriptionIdChatGetResponse,
  ListMinutesForTranscriptionTranscriptionTranscriptionIdMinutesGetData,
  ListMinutesForTranscriptionTranscriptionTranscriptionIdMinutesGetError,
  ListMinutesForTranscriptionTranscriptionTranscriptionIdMinutesGetResponse,
  ListMinuteVersionsMinutesMinuteIdVersionsGetData,
  ListMinuteVersionsMinutesMinuteIdVersionsGetError,
  ListMinuteVersionsMinutesMinuteIdVersionsGetResponse,
  ListTranscriptionsTranscriptionsGetData,
  ListTranscriptionsTranscriptionsGetError,
  ListTranscriptionsTranscriptionsGetResponse,
  SaveTranscriptionTranscriptionsTranscriptionIdPatchData,
  SaveTranscriptionTranscriptionsTranscriptionIdPatchError,
  SaveTranscriptionTranscriptionsTranscriptionIdPatchResponse,
  UpdateDataRetentionUsersDataRetentionPatchData,
  UpdateDataRetentionUsersDataRetentionPatchError,
  UpdateDataRetentionUsersDataRetentionPatchResponse,
} from '../types.gen'

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string
    _infinite?: boolean
    tags?: ReadonlyArray<string>
  },
]

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl:
      options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0]
  if (infinite) {
    params._infinite = infinite
  }
  if (tags) {
    params.tags = tags
  }
  if (options?.body) {
    params.body = options.body
  }
  if (options?.headers) {
    params.headers = options.headers
  }
  if (options?.path) {
    params.path = options.path
  }
  if (options?.query) {
    params.query = options.query
  }
  return [params]
}

export const healthcheckHealthcheckGetQueryKey = (
  options?: Options<HealthcheckHealthcheckGetData>
) => createQueryKey('healthcheckHealthcheckGet', options)

/**
 * Healthcheck
 */
export const healthcheckHealthcheckGetOptions = (
  options?: Options<HealthcheckHealthcheckGetData>
) =>
  queryOptions<
    unknown,
    DefaultError,
    unknown,
    ReturnType<typeof healthcheckHealthcheckGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await healthcheckHealthcheckGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: healthcheckHealthcheckGetQueryKey(options),
  })

export const listTranscriptionsTranscriptionsGetQueryKey = (
  options?: Options<ListTranscriptionsTranscriptionsGetData>
) => createQueryKey('listTranscriptionsTranscriptionsGet', options)

/**
 * List Transcriptions
 *
 * Get paginated metadata for transcriptions for the current user.
 */
export const listTranscriptionsTranscriptionsGetOptions = (
  options?: Options<ListTranscriptionsTranscriptionsGetData>
) =>
  queryOptions<
    ListTranscriptionsTranscriptionsGetResponse,
    ListTranscriptionsTranscriptionsGetError,
    ListTranscriptionsTranscriptionsGetResponse,
    ReturnType<typeof listTranscriptionsTranscriptionsGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listTranscriptionsTranscriptionsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: listTranscriptionsTranscriptionsGetQueryKey(options),
  })

const createInfiniteParams = <
  K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>,
>(
  queryKey: QueryKey<Options>,
  page: K
) => {
  const params = { ...queryKey[0] }
  if (page.body) {
    params.body = {
      ...(queryKey[0].body as any),
      ...(page.body as any),
    }
  }
  if (page.headers) {
    params.headers = {
      ...queryKey[0].headers,
      ...page.headers,
    }
  }
  if (page.path) {
    params.path = {
      ...(queryKey[0].path as any),
      ...(page.path as any),
    }
  }
  if (page.query) {
    params.query = {
      ...(queryKey[0].query as any),
      ...(page.query as any),
    }
  }
  return params as unknown as typeof page
}

export const listTranscriptionsTranscriptionsGetInfiniteQueryKey = (
  options?: Options<ListTranscriptionsTranscriptionsGetData>
): QueryKey<Options<ListTranscriptionsTranscriptionsGetData>> =>
  createQueryKey('listTranscriptionsTranscriptionsGet', options, true)

/**
 * List Transcriptions
 *
 * Get paginated metadata for transcriptions for the current user.
 */
export const listTranscriptionsTranscriptionsGetInfiniteOptions = (
  options?: Options<ListTranscriptionsTranscriptionsGetData>
) =>
  infiniteQueryOptions<
    ListTranscriptionsTranscriptionsGetResponse,
    ListTranscriptionsTranscriptionsGetError,
    InfiniteData<ListTranscriptionsTranscriptionsGetResponse>,
    QueryKey<Options<ListTranscriptionsTranscriptionsGetData>>,
    | number
    | Pick<
      QueryKey<Options<ListTranscriptionsTranscriptionsGetData>>[0],
      'body' | 'headers' | 'path' | 'query'
    >
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<ListTranscriptionsTranscriptionsGetData>>[0],
          'body' | 'headers' | 'path' | 'query'
        > =
          typeof pageParam === 'object'
            ? pageParam
            : {
              query: {
                page: pageParam,
              },
            }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await listTranscriptionsTranscriptionsGet({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        })
        return data
      },
      queryKey: listTranscriptionsTranscriptionsGetInfiniteQueryKey(options),
    }
  )

/**
 * Create Transcription
 *
 * Start a transcription job.
 */
export const createTranscriptionTranscriptionsPostMutation = (
  options?: Partial<Options<CreateTranscriptionTranscriptionsPostData>>
): UseMutationOptions<
  CreateTranscriptionTranscriptionsPostResponse,
  CreateTranscriptionTranscriptionsPostError,
  Options<CreateTranscriptionTranscriptionsPostData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateTranscriptionTranscriptionsPostResponse,
    CreateTranscriptionTranscriptionsPostError,
    Options<CreateTranscriptionTranscriptionsPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createTranscriptionTranscriptionsPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Create Recording
 */
export const createRecordingRecordingsPostMutation = (
  options?: Partial<Options<CreateRecordingRecordingsPostData>>
): UseMutationOptions<
  CreateRecordingRecordingsPostResponse,
  CreateRecordingRecordingsPostError,
  Options<CreateRecordingRecordingsPostData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateRecordingRecordingsPostResponse,
    CreateRecordingRecordingsPostError,
    Options<CreateRecordingRecordingsPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createRecordingRecordingsPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Delete Transcription
 *
 * Delete a specific transcription by ID.
 */
export const deleteTranscriptionTranscriptionsTranscriptionIdDeleteMutation = (
  options?: Partial<
    Options<DeleteTranscriptionTranscriptionsTranscriptionIdDeleteData>
  >
): UseMutationOptions<
  DeleteTranscriptionTranscriptionsTranscriptionIdDeleteResponse,
  DeleteTranscriptionTranscriptionsTranscriptionIdDeleteError,
  Options<DeleteTranscriptionTranscriptionsTranscriptionIdDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteTranscriptionTranscriptionsTranscriptionIdDeleteResponse,
    DeleteTranscriptionTranscriptionsTranscriptionIdDeleteError,
    Options<DeleteTranscriptionTranscriptionsTranscriptionIdDeleteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } =
        await deleteTranscriptionTranscriptionsTranscriptionIdDelete({
          ...options,
          ...fnOptions,
          throwOnError: true,
        })
      return data
    },
  }
  return mutationOptions
}

export const getTranscriptionTranscriptionsTranscriptionIdGetQueryKey = (
  options: Options<GetTranscriptionTranscriptionsTranscriptionIdGetData>
) => createQueryKey('getTranscriptionTranscriptionsTranscriptionIdGet', options)

/**
 * Get Transcription
 *
 * Get a specific transcription by ID.
 */
export const getTranscriptionTranscriptionsTranscriptionIdGetOptions = (
  options: Options<GetTranscriptionTranscriptionsTranscriptionIdGetData>
) =>
  queryOptions<
    GetTranscriptionTranscriptionsTranscriptionIdGetResponse,
    GetTranscriptionTranscriptionsTranscriptionIdGetError,
    GetTranscriptionTranscriptionsTranscriptionIdGetResponse,
    ReturnType<typeof getTranscriptionTranscriptionsTranscriptionIdGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getTranscriptionTranscriptionsTranscriptionIdGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getTranscriptionTranscriptionsTranscriptionIdGetQueryKey(options),
  })

/**
 * Save Transcription
 *
 * Save or update a transcription.
 */
export const saveTranscriptionTranscriptionsTranscriptionIdPatchMutation = (
  options?: Partial<
    Options<SaveTranscriptionTranscriptionsTranscriptionIdPatchData>
  >
): UseMutationOptions<
  SaveTranscriptionTranscriptionsTranscriptionIdPatchResponse,
  SaveTranscriptionTranscriptionsTranscriptionIdPatchError,
  Options<SaveTranscriptionTranscriptionsTranscriptionIdPatchData>
> => {
  const mutationOptions: UseMutationOptions<
    SaveTranscriptionTranscriptionsTranscriptionIdPatchResponse,
    SaveTranscriptionTranscriptionsTranscriptionIdPatchError,
    Options<SaveTranscriptionTranscriptionsTranscriptionIdPatchData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } =
        await saveTranscriptionTranscriptionsTranscriptionIdPatch({
          ...options,
          ...fnOptions,
          throwOnError: true,
        })
      return data
    },
  }
  return mutationOptions
}

export const getRecordingsForTranscriptionTranscriptionsTranscriptionIdRecordingsGetQueryKey =
  (
    options: Options<GetRecordingsForTranscriptionTranscriptionsTranscriptionIdRecordingsGetData>
  ) =>
    createQueryKey(
      'getRecordingsForTranscriptionTranscriptionsTranscriptionIdRecordingsGet',
      options
    )

/**
 * Get Recordings For Transcription
 */
export const getRecordingsForTranscriptionTranscriptionsTranscriptionIdRecordingsGetOptions =
  (
    options: Options<GetRecordingsForTranscriptionTranscriptionsTranscriptionIdRecordingsGetData>
  ) =>
    queryOptions<
      GetRecordingsForTranscriptionTranscriptionsTranscriptionIdRecordingsGetResponse,
      GetRecordingsForTranscriptionTranscriptionsTranscriptionIdRecordingsGetError,
      GetRecordingsForTranscriptionTranscriptionsTranscriptionIdRecordingsGetResponse,
      ReturnType<
        typeof getRecordingsForTranscriptionTranscriptionsTranscriptionIdRecordingsGetQueryKey
      >
    >({
      queryFn: async ({ queryKey, signal }) => {
        const { data } =
          await getRecordingsForTranscriptionTranscriptionsTranscriptionIdRecordingsGet(
            {
              ...options,
              ...queryKey[0],
              signal,
              throwOnError: true,
            }
          )
        return data
      },
      queryKey:
        getRecordingsForTranscriptionTranscriptionsTranscriptionIdRecordingsGetQueryKey(
          options
        ),
    })

export const getUserUsersMeGetQueryKey = (
  options?: Options<GetUserUsersMeGetData>
) => createQueryKey('getUserUsersMeGet', options)

/**
 * Get User
 */
export const getUserUsersMeGetOptions = (
  options?: Options<GetUserUsersMeGetData>
) =>
  queryOptions<
    GetUserUsersMeGetResponse,
    GetUserUsersMeGetError,
    GetUserUsersMeGetResponse,
    ReturnType<typeof getUserUsersMeGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getUserUsersMeGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getUserUsersMeGetQueryKey(options),
  })

/**
 * Update Data Retention
 *
 * Update the data retention period for the current user.
 *
 * Args:
 * data: Request body containing data_retention_days
 * current_user: The current authenticated user
 */
export const updateDataRetentionUsersDataRetentionPatchMutation = (
  options?: Partial<Options<UpdateDataRetentionUsersDataRetentionPatchData>>
): UseMutationOptions<
  UpdateDataRetentionUsersDataRetentionPatchResponse,
  UpdateDataRetentionUsersDataRetentionPatchError,
  Options<UpdateDataRetentionUsersDataRetentionPatchData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateDataRetentionUsersDataRetentionPatchResponse,
    UpdateDataRetentionUsersDataRetentionPatchError,
    Options<UpdateDataRetentionUsersDataRetentionPatchData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await updateDataRetentionUsersDataRetentionPatch({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Update Default Template
 * Set the current user's default template.
 *
 * Exactly one of template_id (a custom template owned by the user) or template_name (a
 * system template) may be provided. Providing neither clears the default. Setting a new
 * default overwrites the previous one, so there is only ever one default per user.
 */
export const updateDefaultTemplateUsersDefaultTemplatePatchMutation = (
  options?: Partial<Options<UpdateDefaultTemplateUsersDefaultTemplatePatchData>>
): UseMutationOptions<
  UpdateDefaultTemplateUsersDefaultTemplatePatchResponse,
  UpdateDefaultTemplateUsersDefaultTemplatePatchError,
  Options<UpdateDefaultTemplateUsersDefaultTemplatePatchData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateDefaultTemplateUsersDefaultTemplatePatchResponse,
    UpdateDefaultTemplateUsersDefaultTemplatePatchError,
    Options<UpdateDefaultTemplateUsersDefaultTemplatePatchData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await updateDefaultTemplateUsersDefaultTemplatePatch({
        ...options,
        ...localOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const listMinutesForTranscriptionTranscriptionTranscriptionIdMinutesGetQueryKey =
  (
    options: Options<ListMinutesForTranscriptionTranscriptionTranscriptionIdMinutesGetData>
  ) =>
    createQueryKey(
      'listMinutesForTranscriptionTranscriptionTranscriptionIdMinutesGet',
      options
    )

/**
 * List Minutes For Transcription
 */
export const listMinutesForTranscriptionTranscriptionTranscriptionIdMinutesGetOptions =
  (
    options: Options<ListMinutesForTranscriptionTranscriptionTranscriptionIdMinutesGetData>
  ) =>
    queryOptions<
      ListMinutesForTranscriptionTranscriptionTranscriptionIdMinutesGetResponse,
      ListMinutesForTranscriptionTranscriptionTranscriptionIdMinutesGetError,
      ListMinutesForTranscriptionTranscriptionTranscriptionIdMinutesGetResponse,
      ReturnType<
        typeof listMinutesForTranscriptionTranscriptionTranscriptionIdMinutesGetQueryKey
      >
    >({
      queryFn: async ({ queryKey, signal }) => {
        const { data } =
          await listMinutesForTranscriptionTranscriptionTranscriptionIdMinutesGet(
            {
              ...options,
              ...queryKey[0],
              signal,
              throwOnError: true,
            }
          )
        return data
      },
      queryKey:
        listMinutesForTranscriptionTranscriptionTranscriptionIdMinutesGetQueryKey(
          options
        ),
    })

/**
 * Create Minute
 */
export const createMinuteTranscriptionTranscriptionIdMinutesPostMutation = (
  options?: Partial<
    Options<CreateMinuteTranscriptionTranscriptionIdMinutesPostData>
  >
): UseMutationOptions<
  CreateMinuteTranscriptionTranscriptionIdMinutesPostResponse,
  CreateMinuteTranscriptionTranscriptionIdMinutesPostError,
  Options<CreateMinuteTranscriptionTranscriptionIdMinutesPostData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateMinuteTranscriptionTranscriptionIdMinutesPostResponse,
    CreateMinuteTranscriptionTranscriptionIdMinutesPostError,
    Options<CreateMinuteTranscriptionTranscriptionIdMinutesPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } =
        await createMinuteTranscriptionTranscriptionIdMinutesPost({
          ...options,
          ...fnOptions,
          throwOnError: true,
        })
      return data
    },
  }
  return mutationOptions
}

export const getMinuteMinutesMinutesIdGetQueryKey = (
  options: Options<GetMinuteMinutesMinutesIdGetData>
) => createQueryKey('getMinuteMinutesMinutesIdGet', options)

/**
 * Get Minute
 */
export const getMinuteMinutesMinutesIdGetOptions = (
  options: Options<GetMinuteMinutesMinutesIdGetData>
) =>
  queryOptions<
    GetMinuteMinutesMinutesIdGetResponse,
    GetMinuteMinutesMinutesIdGetError,
    GetMinuteMinutesMinutesIdGetResponse,
    ReturnType<typeof getMinuteMinutesMinutesIdGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getMinuteMinutesMinutesIdGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getMinuteMinutesMinutesIdGetQueryKey(options),
  })

/**
 * Delete Minute
 */
export const deleteMinuteMinutesMinuteIdDeleteMutation = (
  options?: Partial<Options<DeleteMinuteMinutesMinuteIdDeleteData>>
): UseMutationOptions<
  DeleteMinuteMinutesMinuteIdDeleteResponse,
  DeleteMinuteMinutesMinuteIdDeleteError,
  Options<DeleteMinuteMinutesMinuteIdDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteMinuteMinutesMinuteIdDeleteResponse,
    DeleteMinuteMinutesMinuteIdDeleteError,
    Options<DeleteMinuteMinutesMinuteIdDeleteData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await deleteMinuteMinutesMinuteIdDelete({
        ...options,
        ...localOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const listMinuteVersionsMinutesMinuteIdVersionsGetQueryKey = (
  options: Options<ListMinuteVersionsMinutesMinuteIdVersionsGetData>
) => createQueryKey('listMinuteVersionsMinutesMinuteIdVersionsGet', options)

/**
 * List Minute Versions
 */
export const listMinuteVersionsMinutesMinuteIdVersionsGetOptions = (
  options: Options<ListMinuteVersionsMinutesMinuteIdVersionsGetData>
) =>
  queryOptions<
    ListMinuteVersionsMinutesMinuteIdVersionsGetResponse,
    ListMinuteVersionsMinutesMinuteIdVersionsGetError,
    ListMinuteVersionsMinutesMinuteIdVersionsGetResponse,
    ReturnType<typeof listMinuteVersionsMinutesMinuteIdVersionsGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listMinuteVersionsMinutesMinuteIdVersionsGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: listMinuteVersionsMinutesMinuteIdVersionsGetQueryKey(options),
  })

/**
 * Create Minute Version
 */
export const createMinuteVersionMinutesMinuteIdVersionsPostMutation = (
  options?: Partial<Options<CreateMinuteVersionMinutesMinuteIdVersionsPostData>>
): UseMutationOptions<
  CreateMinuteVersionMinutesMinuteIdVersionsPostResponse,
  CreateMinuteVersionMinutesMinuteIdVersionsPostError,
  Options<CreateMinuteVersionMinutesMinuteIdVersionsPostData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateMinuteVersionMinutesMinuteIdVersionsPostResponse,
    CreateMinuteVersionMinutesMinuteIdVersionsPostError,
    Options<CreateMinuteVersionMinutesMinuteIdVersionsPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createMinuteVersionMinutesMinuteIdVersionsPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Delete Minute Version
 */
export const deleteMinuteVersionMinuteVersionsMinuteVersionIdDeleteMutation = (
  options?: Partial<
    Options<DeleteMinuteVersionMinuteVersionsMinuteVersionIdDeleteData>
  >
): UseMutationOptions<
  unknown,
  DeleteMinuteVersionMinuteVersionsMinuteVersionIdDeleteError,
  Options<DeleteMinuteVersionMinuteVersionsMinuteVersionIdDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    DeleteMinuteVersionMinuteVersionsMinuteVersionIdDeleteError,
    Options<DeleteMinuteVersionMinuteVersionsMinuteVersionIdDeleteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } =
        await deleteMinuteVersionMinuteVersionsMinuteVersionIdDelete({
          ...options,
          ...fnOptions,
          throwOnError: true,
        })
      return data
    },
  }
  return mutationOptions
}

export const getMinuteVersionMinuteVersionsMinuteVersionIdGetQueryKey = (
  options: Options<GetMinuteVersionMinuteVersionsMinuteVersionIdGetData>
) => createQueryKey('getMinuteVersionMinuteVersionsMinuteVersionIdGet', options)

/**
 * Get Minute Version
 */
export const getMinuteVersionMinuteVersionsMinuteVersionIdGetOptions = (
  options: Options<GetMinuteVersionMinuteVersionsMinuteVersionIdGetData>
) =>
  queryOptions<
    GetMinuteVersionMinuteVersionsMinuteVersionIdGetResponse,
    GetMinuteVersionMinuteVersionsMinuteVersionIdGetError,
    GetMinuteVersionMinuteVersionsMinuteVersionIdGetResponse,
    ReturnType<typeof getMinuteVersionMinuteVersionsMinuteVersionIdGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getMinuteVersionMinuteVersionsMinuteVersionIdGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getMinuteVersionMinuteVersionsMinuteVersionIdGetQueryKey(options),
  })

export const getTemplatesTemplatesGetQueryKey = (
  options?: Options<GetTemplatesTemplatesGetData>
) => createQueryKey('getTemplatesTemplatesGet', options)

/**
 * Get Templates
 *
 * Get metadata for all templates.
 */
export const getTemplatesTemplatesGetOptions = (
  options?: Options<GetTemplatesTemplatesGetData>
) =>
  queryOptions<
    GetTemplatesTemplatesGetResponse,
    GetTemplatesTemplatesGetError,
    GetTemplatesTemplatesGetResponse,
    ReturnType<typeof getTemplatesTemplatesGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getTemplatesTemplatesGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getTemplatesTemplatesGetQueryKey(options),
  })

export const getUserTemplatesUserTemplatesGetQueryKey = (
  options?: Options<GetUserTemplatesUserTemplatesGetData>
) => createQueryKey('getUserTemplatesUserTemplatesGet', options)

/**
 * Get User Templates
 */
export const getUserTemplatesUserTemplatesGetOptions = (
  options?: Options<GetUserTemplatesUserTemplatesGetData>
) =>
  queryOptions<
    GetUserTemplatesUserTemplatesGetResponse,
    GetUserTemplatesUserTemplatesGetError,
    GetUserTemplatesUserTemplatesGetResponse,
    ReturnType<typeof getUserTemplatesUserTemplatesGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getUserTemplatesUserTemplatesGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getUserTemplatesUserTemplatesGetQueryKey(options),
  })

/**
 * Create User Template
 */
export const createUserTemplateUserTemplatesPostMutation = (
  options?: Partial<Options<CreateUserTemplateUserTemplatesPostData>>
): UseMutationOptions<
  unknown,
  CreateUserTemplateUserTemplatesPostError,
  Options<CreateUserTemplateUserTemplatesPostData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    CreateUserTemplateUserTemplatesPostError,
    Options<CreateUserTemplateUserTemplatesPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createUserTemplateUserTemplatesPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Delete User Template
 */
export const deleteUserTemplateUserTemplatesTemplateIdDeleteMutation = (
  options?: Partial<
    Options<DeleteUserTemplateUserTemplatesTemplateIdDeleteData>
  >
): UseMutationOptions<
  unknown,
  DeleteUserTemplateUserTemplatesTemplateIdDeleteError,
  Options<DeleteUserTemplateUserTemplatesTemplateIdDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    DeleteUserTemplateUserTemplatesTemplateIdDeleteError,
    Options<DeleteUserTemplateUserTemplatesTemplateIdDeleteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteUserTemplateUserTemplatesTemplateIdDelete({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getUserTemplateUserTemplatesTemplateIdGetQueryKey = (
  options: Options<GetUserTemplateUserTemplatesTemplateIdGetData>
) => createQueryKey('getUserTemplateUserTemplatesTemplateIdGet', options)

/**
 * Get User Template
 */
export const getUserTemplateUserTemplatesTemplateIdGetOptions = (
  options: Options<GetUserTemplateUserTemplatesTemplateIdGetData>
) =>
  queryOptions<
    GetUserTemplateUserTemplatesTemplateIdGetResponse,
    GetUserTemplateUserTemplatesTemplateIdGetError,
    GetUserTemplateUserTemplatesTemplateIdGetResponse,
    ReturnType<typeof getUserTemplateUserTemplatesTemplateIdGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getUserTemplateUserTemplatesTemplateIdGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getUserTemplateUserTemplatesTemplateIdGetQueryKey(options),
  })

/**
 * Edit User Template
 */
export const editUserTemplateUserTemplatesTemplateIdPatchMutation = (
  options?: Partial<Options<EditUserTemplateUserTemplatesTemplateIdPatchData>>
): UseMutationOptions<
  unknown,
  EditUserTemplateUserTemplatesTemplateIdPatchError,
  Options<EditUserTemplateUserTemplatesTemplateIdPatchData>
> => {
  const mutationOptions: UseMutationOptions<
    unknown,
    EditUserTemplateUserTemplatesTemplateIdPatchError,
    Options<EditUserTemplateUserTemplatesTemplateIdPatchData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await editUserTemplateUserTemplatesTemplateIdPatch({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Duplicate User Template
 */
export const duplicateUserTemplateUserTemplatesTemplateIdDuplicatePostMutation =
  (
    options?: Partial<
      Options<DuplicateUserTemplateUserTemplatesTemplateIdDuplicatePostData>
    >
  ): UseMutationOptions<
    DuplicateUserTemplateUserTemplatesTemplateIdDuplicatePostResponse,
    DuplicateUserTemplateUserTemplatesTemplateIdDuplicatePostError,
    Options<DuplicateUserTemplateUserTemplatesTemplateIdDuplicatePostData>
  > => {
    const mutationOptions: UseMutationOptions<
      DuplicateUserTemplateUserTemplatesTemplateIdDuplicatePostResponse,
      DuplicateUserTemplateUserTemplatesTemplateIdDuplicatePostError,
      Options<DuplicateUserTemplateUserTemplatesTemplateIdDuplicatePostData>
    > = {
      mutationFn: async (fnOptions) => {
        const { data } =
          await duplicateUserTemplateUserTemplatesTemplateIdDuplicatePost({
            ...options,
            ...fnOptions,
            throwOnError: true,
          })
        return data
      },
    }
    return mutationOptions
  }

/**
 * Delete Chats
 */
export const deleteChatsTranscriptionsTranscriptionIdChatDeleteMutation = (
  options?: Partial<
    Options<DeleteChatsTranscriptionsTranscriptionIdChatDeleteData>
  >
): UseMutationOptions<
  DeleteChatsTranscriptionsTranscriptionIdChatDeleteResponse,
  DeleteChatsTranscriptionsTranscriptionIdChatDeleteError,
  Options<DeleteChatsTranscriptionsTranscriptionIdChatDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteChatsTranscriptionsTranscriptionIdChatDeleteResponse,
    DeleteChatsTranscriptionsTranscriptionIdChatDeleteError,
    Options<DeleteChatsTranscriptionsTranscriptionIdChatDeleteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteChatsTranscriptionsTranscriptionIdChatDelete(
        {
          ...options,
          ...fnOptions,
          throwOnError: true,
        }
      )
      return data
    },
  }
  return mutationOptions
}

export const listChatTranscriptionsTranscriptionIdChatGetQueryKey = (
  options: Options<ListChatTranscriptionsTranscriptionIdChatGetData>
) => createQueryKey('listChatTranscriptionsTranscriptionIdChatGet', options)

/**
 * List Chat
 */
export const listChatTranscriptionsTranscriptionIdChatGetOptions = (
  options: Options<ListChatTranscriptionsTranscriptionIdChatGetData>
) =>
  queryOptions<
    ListChatTranscriptionsTranscriptionIdChatGetResponse,
    ListChatTranscriptionsTranscriptionIdChatGetError,
    ListChatTranscriptionsTranscriptionIdChatGetResponse,
    ReturnType<typeof listChatTranscriptionsTranscriptionIdChatGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listChatTranscriptionsTranscriptionIdChatGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: listChatTranscriptionsTranscriptionIdChatGetQueryKey(options),
  })

/**
 * Create Chat
 */
export const createChatTranscriptionsTranscriptionIdChatPostMutation = (
  options?: Partial<
    Options<CreateChatTranscriptionsTranscriptionIdChatPostData>
  >
): UseMutationOptions<
  CreateChatTranscriptionsTranscriptionIdChatPostResponse,
  CreateChatTranscriptionsTranscriptionIdChatPostError,
  Options<CreateChatTranscriptionsTranscriptionIdChatPostData>
> => {
  const mutationOptions: UseMutationOptions<
    CreateChatTranscriptionsTranscriptionIdChatPostResponse,
    CreateChatTranscriptionsTranscriptionIdChatPostError,
    Options<CreateChatTranscriptionsTranscriptionIdChatPostData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await createChatTranscriptionsTranscriptionIdChatPost({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Delete Chat
 *
 * Delete a specific transcription by ID.
 */
export const deleteChatTranscriptionsTranscriptionIdChatChatIdDeleteMutation = (
  options?: Partial<
    Options<DeleteChatTranscriptionsTranscriptionIdChatChatIdDeleteData>
  >
): UseMutationOptions<
  DeleteChatTranscriptionsTranscriptionIdChatChatIdDeleteResponse,
  DeleteChatTranscriptionsTranscriptionIdChatChatIdDeleteError,
  Options<DeleteChatTranscriptionsTranscriptionIdChatChatIdDeleteData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteChatTranscriptionsTranscriptionIdChatChatIdDeleteResponse,
    DeleteChatTranscriptionsTranscriptionIdChatChatIdDeleteError,
    Options<DeleteChatTranscriptionsTranscriptionIdChatChatIdDeleteData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } =
        await deleteChatTranscriptionsTranscriptionIdChatChatIdDelete({
          ...options,
          ...fnOptions,
          throwOnError: true,
        })
      return data
    },
  }
  return mutationOptions
}

export const getChatTranscriptionsTranscriptionIdChatChatIdGetQueryKey = (
  options: Options<GetChatTranscriptionsTranscriptionIdChatChatIdGetData>
) =>
  createQueryKey('getChatTranscriptionsTranscriptionIdChatChatIdGet', options)

/**
 * Get Chat
 */
export const getChatTranscriptionsTranscriptionIdChatChatIdGetOptions = (
  options: Options<GetChatTranscriptionsTranscriptionIdChatChatIdGetData>
) =>
  queryOptions<
    GetChatTranscriptionsTranscriptionIdChatChatIdGetResponse,
    GetChatTranscriptionsTranscriptionIdChatChatIdGetError,
    GetChatTranscriptionsTranscriptionIdChatChatIdGetResponse,
    ReturnType<typeof getChatTranscriptionsTranscriptionIdChatChatIdGetQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getChatTranscriptionsTranscriptionIdChatChatIdGet({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey:
      getChatTranscriptionsTranscriptionIdChatChatIdGetQueryKey(options),
  })
